services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 4815162342
      MYSQL_DATABASE: test_can_rate
      MYSQL_USER: canrate
      MYSQL_PASSWORD: c5Lq!._bX4gF)ju!
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: canrate
      PMA_PASSWORD: c5Lq!._bX4gF)ju!
    ports:
      - "9000:80"
    depends_on:
      - mariadb
